// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8Mg4B7bVx9HWIjqGFMRbF8KVWgxYVWXA',
    appId: '1:94534198129:web:de6d9ca4a197b811e78cd0',
    messagingSenderId: '94534198129',
    projectId: 'quizapp-eaf88',
    authDomain: 'quizapp-eaf88.firebaseapp.com',
    storageBucket: 'quizapp-eaf88.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0ZirX3NGs7pBDhjzyuJMSKFGaMnRna3I',
    appId: '1:94534198129:android:22c31603d37dfbc2e78cd0',
    messagingSenderId: '94534198129',
    projectId: 'quizapp-eaf88',
    storageBucket: 'quizapp-eaf88.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnZUd_YbZsh-S3IK8ZA2_msqKd5g02LAg',
    appId: '1:94534198129:ios:31d807cdce6c4a54e78cd0',
    messagingSenderId: '94534198129',
    projectId: 'quizapp-eaf88',
    storageBucket: 'quizapp-eaf88.appspot.com',
    iosClientId: '94534198129-8hpt0vs65qndqlj5b5jb42fuvr8ad32p.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizApp',
  );
}
